config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root 'root#index'
  root 'tutor#index', as: 'home'

  resources :tutor
  resources :subject
  resources :took

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/available_block.rb
class AvailableBlock < ApplicationRecord
  belongs_to :tutor
end

app/models/subject.rb
class Subject < ApplicationRecord
	has_many :took
	has_many :tutor, through: :took 
end

app/models/took.rb
class Took < ApplicationRecord
	belongs_to :tutor
	belongs_to :subject

  def subject
    Subject.find_by_id(self[:subject_id])
  end
end

app/models/tutor.rb
class Tutor < ApplicationRecord

  has_many :took
  has_many :tutor, through: :took
  has_many :available_block
  validates :name, presence: true

  def available?
    available_block.each do |block|
      if block.day == today && now.between?(block.start, block.end)
        return "Available"
      end
    end
    return "Unavailable"
  end

  private 

  def today
    Date.today.wday
  end

  def now
    Time.now.strftime('%H:%M:%S')
  end
end
 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/subject_controller.rb
class SubjectController < ApplicationController
  def index
    @subject = Subject.where(:area => params[:area])
  end
end

app/controllers/took_controller.rb
class TookController < ApplicationController
  def index
    @took = Took.where(:subject_id => params[:subject_id]).order(grade: :desc)
  end
end

app/controllers/tutor_controller.rb
class TutorController < ApplicationController
	def index
    @tutor = Tutor.order("RANDOM()").limit(5)
  end

  def show
    @tutor = Tutor.find(params[:id])
  end

  def create
    @tutor = Tutor.new(tutor_params)

    @tutor.save

    redirect_to @tutor
  end

  private

  def tutor_params
    params.require(:tutor).permit(
      :name,
      :gender,
      :occupation,
      :major,
      :age,
      :rate,
      :gpa,
      :score)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/subject_helper.rb
module SubjectHelper
end

app/helpers/took_helper.rb
module TookHelper
end

app/helpers/tutor_helper.rb
module TutorHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <title>Startup Challenge</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'https://stackpath.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css' %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <a class="navbar-brand" href="<%= home_path %>">Startup Challenge</a>
    </nav>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/subject/index.html.erb
<h3 align="center" style="padding-top: 3em;">
  Selecciona la materia para la cual quieres asesorías
</h3>

<hr style="width: 100%; color: grey; height: 1px; background-color:grey;"/>

<div class="mx-auto dynamic" align="center">
    <% @subject.each do |subject| %>
    <a class="dropdown-item" href="<%= took_index_path(:subject_id => subject.id) %>">
      <%= subject.name %>
    </a>
    <% end %>
</div>

app/views/took/index.html.erb
<div class="container" style="margin-top: 5em;">
  <ul class="list-group">
    <li class="list-group-item active">
      Tutores de <b><%= @took.first.subject.name %></b>
    </li>
    <% @took.each do |took| %>
        <h5>
           <span class="badge badge-primary badge-pill"><%= took.grade.to_int %></span>
           <%= took.tutor.name %>
           (<font color="#36f"><%= took.tutor.major %></font>) - 
           <% if took.tutor.available? == "Unavailable" %>
               <font color="red">
           <% else %>
               <font color="lime">
           <% end %>
           <%= took.tutor.available?%></font>
           <%= link_to '<button type="button" class="btn btn-info">More Info</button>'.html_safe, tutor_path(took.tutor) %>
        </h5>
         
        <hr style="width: 100%; color: black; height: 1px; background-color:black;"/>
    <% end %>
  </ul>
</div>

app/views/tutor/_dropdown.html.erb
<hr style="width: 100%; color: grey; height: 1px; background-color:grey;"/>

<div class="dropdown">
      <a class="dropdown-item" href="<%= subject_index_path(:area => 'FISMA') %>">IFI</a>
      <a class="dropdown-item" href="<%= subject_index_path(:area => 'CS') %>">ISD</a>
      <a class="dropdown-item" href="<%= subject_index_path(:area => 'CS') %>">ITC</a>
      <a class="dropdown-item" href="<%= subject_index_path(:area => 'E&G') %>">LAE</a>
      <a class="dropdown-item" href="<%= subject_index_path(:area => 'RI') %>">LRI</a>
</div>

app/views/tutor/index.html.erb
<h3 align="center" style="padding-top: 3em;">
  Busca asesores para materias de tu carrera
</h3>

<div class="mx-auto dynamic" align="center">
  <%= render partial: 'dropdown' %>
</div>

<div class="container" style="margin-top: 1em;">
  <ul class="list-group">
    <li class="list-group-item active">Tutores Destacados</li>
    <% @tutor.each do |tutor| %>
        <h5>
           <%= tutor.name %>
           (<font color="#36f"><%= tutor.major %></font>) - 
           <% if tutor.available? == "Unavailable" %>
               <font color="red">
           <% else %>
               <font color="lime">
           <% end %>
           <%= tutor.available?%></font>
           <%= link_to '<button type="button" class="btn btn-info">More Info</button>'.html_safe, tutor_path(tutor) %>
        </h5>
         
        <hr style="width: 100%; color: black; height: 1px; background-color:black;"/>
    <% end %>
  </ul>
</div>

app/views/tutor/show.html.erb
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<div class="username" style="padding-top: 100px">
    <div class="row">
        <div class="col-2">
            <img id="<%= @tutor.available? %>" src="https://loremflickr.com/164/164/<%= @tutor.gender %>"/>
        </div>
        <div class="col-8" style="padding-top: 35px">
            <h2>
                <%= @tutor.name.titleize %> -
                <% if @tutor.available? %>
                    <font color="red">
                <% else %>
                    <font color="lime">
                <% end %>
                <%= @tutor.available?%></font>
            </h2>
            <h2>
                <% @tutor.score.to_int.times do %>
                    <span class="fa fa-star checked"></span>
                <% end %>
                <% (5 - @tutor.score).to_int.times do %>
                    <span class="fa fa-star"></span>
                <% end %>
            </h2>
        </div>
    </div>
    <div class="row">
        <div class="col-8">
            <h2>Cuota: $<%= @tutor.rate %></h2>
        </div>
    </div>
    <div class="row">
        <div class="col-8">
            <h2>Materias:</h2>
        </div>
    </div>
    <div class="row" style="padding-left: 30px">
        <ul class="list-group">
            <% @tutor.took.each do |course| %>
                <li class="list-group-item justify-content-between align-items-center">
                    <%= course.subject.name %>
                    <span class="badge badge-primary badge-pill"><%= course.grade.to_int %></span>
                </li>
            <% end %>
        </ul>
    </div>
</div>